me: apply

on:
  workflow_dispatch:

concurrency: apply

env:
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

jobs:
  jira:
    needs: [ testjob ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: set-env-info
        run: |
          echo "GIT_REPO=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')" >> $GITHUB_ENV
          echo "GITHUB_WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW} | sed -e 's|.*/||')" >> $GITHUB_ENV
      - name: jira-notification-action
        uses: champ-oss/jira-notification@v1.0.3-c4c4e52
        with:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_PROJECT: TEST
          GIT_REPO: ${{ env.GIT_REPO }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          GITHUB_WORKFLOW_NAME: ${{ env.GITHUB_WORKFLOW_NAME }}
  testjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
 	  exit 1

