name: update
description: https://github.com/champ-oss/jira-notication
inputs:
  GIT_REPO:
    description: 'tagging repo for failure'
    required: true
    default: 'TEST'
  GITHUB_WORKFLOW_NAME:
    description: 'workflow causing failure'
    required: true
    default: 'testing'
  JIRA_PROJECT:
    description: 'jira project to open ticket'
    required: true
    default: 'CTEST'
  JIRA_TOKEN:
    description: 'token used to auth with jira'
    required: true
  JIRA_USER:
    description: 'user used to auth with jira'
    required: true
  JIRA_HOST:
    description: 'jira host'
    required: true

runs:
  using: "composite"
  steps:
    - name: install jira lib
      shell: bash
      run: pip3 install atlassian_python_api==3.27.0
    - name: run python script
      shell: bash
      env:
        JIRA_PROJECT: ${{ inputs.JIRA_PROJECT }}
        GIT_REPO: ${{ inputs.GIT_REPO }}
        JIRA_TOKEN: ${{ inputs.JIRA_TOKEN }}
        JIRA_USER: ${{ inputs.JIRA_USER }}
        JIRA_HOST: ${{ inputs.JIRA_HOST }}
        GITHUB_WORKFLOW_NAME: ${{ inputs.GITHUB_WORKFLOW_NAME }}
      run: |
        python ${GITHUB_ACTION_PATH}/jira-notification.py
