name: update
description: https://github.com/champ-oss/jira-notication
inputs:
  JIRA_REPO:
    description: 'tagging repo for failure'
    required: true
    default: 'TEST'
  JIRA_PROJECT:
    description: 'jira project to open ticket'
    required: true
    default: 'CTEST'
  JIRA_TOKEN:
    description: 'token used to auth with jira rest api'
    required: true
  JIRA_HOST:
    description: 'rest api jira host'
    required: true

runs:
  using: "composite"
  steps:
    - name: run python script
      shell: bash
      env:
        JIRA_PROJECT: ${{ inputs.JIRA_PROJECT }}
        JIRA_REPO: ${{ inputs.JIRA_REPO }}
        JIRA_TOKEN: ${{ inputs.JIRA_TOKEN }}
        JIRA_HOST: ${{ inputs.JIRA_HOST }}
      run: |
        python ${GITHUB_ACTION_PATH}/jira-notification.py